table dim_orders_flags
	lineageTag: dc4ad983-e17f-4ebb-bd75-b834261f55e9

	column flag_key
		dataType: int64
		formatString: 0
		lineageTag: 1fcf4820-4ee9-47dc-9776-c6dd4bd83125
		summarizeBy: none
		sourceColumn: flag_key

		annotation SummarizationSetBy = Automatic

	column channel_id
		dataType: int64
		formatString: 0
		lineageTag: 38faaa1d-2ced-4ad1-b734-d9c16cb21386
		summarizeBy: none
		sourceColumn: channel_id

		annotation SummarizationSetBy = Automatic

	column channel_name
		dataType: string
		lineageTag: 23afb09e-d4d1-41f5-a978-a6c5489a7c4b
		summarizeBy: none
		sourceColumn: channel_name

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 22b0ff75-75e1-4a5b-adea-0a45342baa0f
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column priority
		dataType: string
		lineageTag: 0de25b78-8673-4d60-99ac-c0024f6c0442
		summarizeBy: none
		sourceColumn: priority

		annotation SummarizationSetBy = Automatic

	partition dim_orders_flags = m
		mode: import
		queryGroup: 02_Dimensions
		source =
				let
				    Source = Orders,
				    #"Removed Columns" = Table.RemoveColumns(Source,{"OrderID", "CustomerName", "CustomerCity", "RegionName", "ShipToCity", "BillToCity", "OrderDate", "OrderTotal"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "flag_key"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"flag_key", "OrderChannel", "Status", "Priority"}),
				    #"Merged Queries" = Table.NestedJoin(#"Reordered Columns", {"OrderChannel"}, Channels, {"channel_id"}, "Channels", JoinKind.LeftOuter),
				    #"Expanded Channels" = Table.ExpandTableColumn(#"Merged Queries", "Channels", {"channel_name"}, {"Channels.channel_name"}),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Expanded Channels",{"flag_key", "OrderChannel", "Channels.channel_name", "Status", "Priority"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Reordered Columns1",{{"OrderChannel", "channel_id"}, {"Channels.channel_name", "channel_name"}, {"Status", "status"}, {"Priority", "priority"}})
				in
				    #"Renamed Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

