// Guards for the Capacitor / Android packaging: the app must bundle its own
// web content (never a remote site), request no permissions, target a
// Play-compliant API level and ship real (non-template) icons.
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { beforeAll, describe, expect, test } from 'vitest';
import { hashOf } from '../scripts/stamp-assets.mjs';

const root = join(import.meta.dirname, '..');
const read = (file) => readFileSync(join(root, file), 'utf8');

describe('capacitor.config.json', () => {
    const config = JSON.parse(read('capacitor.config.json'));

    test('identity and packaged web content', () => {
        expect(config.appId).toBe('com.saikumar.sqlbuilder');
        expect(config.appName).toBe('SQL Builder Pro Lite');
        expect(config.webDir).toBe('www');
    });

    test('never loads a remote site (no server.url) and blocks mixed content', () => {
        expect(config.server?.url).toBeUndefined();
        expect(config.server?.cleartext).not.toBe(true);
        expect(config.android.allowMixedContent).toBe(false);
    });
});

describe('www/ (content packaged into the app)', () => {
    beforeAll(() => {
        execFileSync(process.execPath, [join(root, 'scripts/build-mobile.mjs')], { cwd: root, stdio: 'pipe' });
    }, 60000);

    test('contains the app, the native entry point and a strict CSP', () => {
        const html = read('www/index.html');
        expect(html).toMatch(/<meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self';/);
        expect(html).toContain(`src="dist/sqlbuilder.js?v=${hashOf('dist/sqlbuilder.js', join(root, 'www'))}"`);
        expect(html).toContain(`href="style.css?v=${hashOf('style.css', join(root, 'www'))}"`);
        expect(html).not.toMatch(/rel="manifest"|serviceWorker/);
        expect(html).not.toMatch(/https?:\/\/(?!www\.w3\.org)/);
        const bundle = read('www/dist/sqlbuilder.js');
        expect(bundle).toContain('backButton');
        expect(bundle).not.toMatch(/vercel\.app/);
    });

    test('the website bundle does not include Capacitor', () => {
        expect(read('dist/sqlbuilder.js')).not.toMatch(/capacitor/i);
    });
});

describe('Android project', () => {
    const manifest = read('android/app/src/main/AndroidManifest.xml');
    const gradleVars = read('android/variables.gradle');
    const appGradle = read('android/app/build.gradle');

    test('targets API 36+ (Google Play requirement from 31 Aug 2026)', () => {
        const target = Number(gradleVars.match(/targetSdkVersion = (\d+)/)[1]);
        const compile = Number(gradleVars.match(/compileSdkVersion = (\d+)/)[1]);
        expect(target).toBeGreaterThanOrEqual(36);
        expect(compile).toBeGreaterThanOrEqual(target);
    });

    test('requests no permissions and keeps data out of cloud backups', () => {
        expect(manifest).not.toMatch(/<uses-permission/);
        expect(manifest).toContain('android:allowBackup="false"');
        expect(manifest).toContain('android:usesCleartextTraffic="false"');
    });

    test('FileProvider exposes only the export cache folder', () => {
        const paths = read('android/app/src/main/res/xml/file_paths.xml');
        expect(paths).toContain('<cache-path name="exports" path="exports/" />');
        expect(paths).not.toMatch(/external-path|root-path|files-path/);
    });

    test('version comes from package.json; signing secrets are not in the repo', () => {
        expect(appGradle).toContain("new JsonSlurper().parse(file('../../package.json'))");
        expect(appGradle).toContain('versionCode appVersionCode');
        expect(existsSync(join(root, 'android/keystore.properties'))).toBe(false);
        expect(read('android/.gitignore')).toMatch(/keystore\.properties[\s\S]*\*\.jks[\s\S]*\*\.keystore/);
        expect(appGradle).not.toMatch(/storePassword\s+['"]/);
    });

    test('ships generated brand icons, not the Capacitor template placeholders', () => {
        const res = join(root, 'android/app/src/main/res');
        const allFiles = readdirSync(res, { recursive: true }).map(String);
        expect(allFiles.filter(f => f.endsWith('splash.png'))).toEqual([]);
        expect(read('android/app/src/main/res/drawable/ic_launcher_foreground.xml')).toContain('Generated by scripts/generate-icons.mjs');
        expect(read('android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml')).toContain('<monochrome');
        expect(read('android/app/src/main/res/values/ic_launcher_background.xml')).toContain('#1D5FD6');
        for (const density of ['mdpi', 'hdpi', 'xhdpi', 'xxhdpi', 'xxxhdpi']) {
            expect(existsSync(join(res, `mipmap-${density}/ic_launcher.png`))).toBe(true);
            expect(existsSync(join(res, `mipmap-${density}/ic_launcher_round.png`))).toBe(true);
        }
    });

    test('app name is defined in one place per platform', () => {
        const strings = read('android/app/src/main/res/values/strings.xml');
        expect(strings).toContain('<string name="app_name">SQL Builder Pro Lite</string>');
    });
});
