// The contract between the app and a database engine. The SQL Lab only talks
// to an engine through a client (client.js), which sends these operations to
// the engine adapter (sqlite-adapter.js) inside the database worker:
//
//   info()                         engine name/version, persistence, open db
//   create(id), open(id), close(), remove(id), removeAll(), duplicate(from, to)
//   execute(sql, { pageSize })     { results: StatementResult[], omitted, statements, changes, error, inTransaction }
//   fetchPage(cursor, { pageSize }), closeCursor(cursor)
//   schema()                       tables and views of the open database
//   countRows(name)                rows in one table or view (open cursors are kept)
//   exportFile(id), importFile(id, bytes)
//   runScript(sql)                 an imported script, in one transaction
//   insertRows({ setup, sql, rows }) imported rows, bound to one INSERT, in one transaction
//
// Imports (importer.js) are two operations on top of these: previewImport
// (reads, changes nothing) and runImport.
//
// A StatementResult is { sql, kind, columns, rows, more, cursor, rowsAffected,
// durationMs, statement, line }. A long script returns its first results and
// its last (`omitted` counts the rest). rowsAffected is null unless the engine
// reported it; durationMs is measured by the engine around that statement.

/** An error the engine reports, with what's known about where it happened. */
export class DatabaseError extends Error {
    /**
     * @param {string} message
     * @param {{ code?: string, line?: number, column?: number, statement?: number, row?: number }} [details]
     */
    constructor(message, details = {}) {
        super(message);
        this.name = 'DatabaseError';
        this.code = details.code || 'ERROR';
        if (details.line !== undefined) this.line = details.line;
        if (details.column !== undefined) this.column = details.column;
        if (details.statement !== undefined) this.statement = details.statement;
        // The data row (1-based) an import stopped at
        if (details.row !== undefined) this.row = details.row;
    }
}

/**
 * The 1-based line and column of a byte offset in UTF-8 text.
 * @param {Uint8Array} bytes
 * @param {number} offset
 */
export function positionAt(bytes, offset) {
    const before = new TextDecoder().decode(bytes.subarray(0, Math.max(0, Math.min(bytes.length, offset))));
    const lines = before.split('\n');
    return { line: lines.length, column: [...lines[lines.length - 1]].length + 1 };
}

/** What a database file is called in storage. */
export const databaseFileName = (/** @type {string} */ id) => `db-${id}.sqlite3`;

/** Ids are generated by the app; anything else is refused before reaching storage. */
export const isDatabaseId = (/** @type {unknown} */ id) => typeof id === 'string' && /^[a-z0-9][a-z0-9-]{3,39}$/.test(id);
