// Generates every app icon from one definition, so the Android launcher icon,
// splash screen, PWA icons and Play Store graphics all match the database
// symbol used in the web header.
//
//   node scripts/generate-icons.mjs
//
// Outputs (committed):
//   resources/icon.svg                         master artwork (full bleed)
//   android/app/src/main/res/drawable/*.xml    adaptive icon layers + splash (vectors)
//   android/app/src/main/res/mipmap-*/*.png    legacy launcher icons (Android 7.x)
//   icons/*.png                                PWA icons
//   store/*.png                                Google Play icon + feature graphic
import sharp from 'sharp';
import { mkdirSync, rmSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const root = join(import.meta.dirname, '..');
const res = join(root, 'android/app/src/main/res');

export const BRAND = {
    background: '#1D5FD6',   // --accent in style.css (light theme)
    foreground: '#FFFFFF',
    name: 'SQL Builder Pro Lite',
    tagline: 'Build SQL visually. Offline. Private.'
};

// The database symbol from the web header (24×24 units, 2-unit stroke)
const SYMBOL_PATHS = [
    'M3,5 a9,3 0 1,0 18,0 a9,3 0 1,0 -18,0',          // top ellipse
    'M3,5 v14 c0,1.66 4,3 9,3 s9,-1.34 9,-3 V5',        // body
    'M3,12 c0,1.66 4,3 9,3 s9,-1.34 9,-3'               // middle band
];

// Adaptive icons are 108dp with a 66dp safe zone; the symbol spans 40dp.
const ADAPTIVE = { scale: 40 / 24, offset: 54 - 20 };

// --------------------------------------------------------------- Android XML

function vectorDrawable({ size = 108, color, viewport = 108, scale = ADAPTIVE.scale, offset = ADAPTIVE.offset }) {
    const paths = SYMBOL_PATHS.map(d => `        <path
            android:pathData="${d}"
            android:fillColor="#00000000"
            android:strokeColor="${color}"
            android:strokeWidth="2"
            android:strokeLineCap="round"
            android:strokeLineJoin="round" />`).join('\n');
    return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate-icons.mjs — edit the script, not this file. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="${size}dp"
    android:height="${size}dp"
    android:viewportWidth="${viewport}"
    android:viewportHeight="${viewport}">
    <group
        android:scaleX="${scale.toFixed(4)}"
        android:scaleY="${scale.toFixed(4)}"
        android:translateX="${offset}"
        android:translateY="${offset}">
${paths}
    </group>
</vector>
`;
}

const ADAPTIVE_ICON = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate-icons.mjs -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
`;

// ------------------------------------------------------------------ SVG / PNG

/** SVG artwork: `shape` = square | rounded | circle; symbol size as a fraction of the canvas. */
function artwork(size, { shape = 'square', symbolFraction = 40 / 108, background = BRAND.background } = {}) {
    const scale = (size * symbolFraction) / 24;
    const offset = (size - 24 * scale) / 2;
    const bg = shape === 'circle'
        ? `<circle cx="${size / 2}" cy="${size / 2}" r="${size / 2}" fill="${background}"/>`
        : `<rect width="${size}" height="${size}" rx="${shape === 'rounded' ? size * 0.18 : 0}" fill="${background}"/>`;
    return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">
  ${bg}
  <g transform="translate(${offset} ${offset}) scale(${scale})" fill="none" stroke="${BRAND.foreground}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
    ${SYMBOL_PATHS.map(d => `<path d="${d}"/>`).join('\n    ')}
  </g>
</svg>
`;
}

function featureGraphic() {
    const iconSize = 260;
    const scale = (iconSize * 0.62) / 24;
    const ox = 110 + (iconSize - 24 * scale) / 2;
    const oy = 120 + (iconSize - 24 * scale) / 2;
    return `<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="500" viewBox="0 0 1024 500">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="#1D5FD6"/>
      <stop offset="1" stop-color="#123E91"/>
    </linearGradient>
  </defs>
  <rect width="1024" height="500" fill="url(#bg)"/>
  <rect x="110" y="120" width="${iconSize}" height="${iconSize}" rx="48" fill="#FFFFFF" fill-opacity="0.12"/>
  <g transform="translate(${ox} ${oy}) scale(${scale})" fill="none" stroke="#FFFFFF" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
    ${SYMBOL_PATHS.map(d => `<path d="${d}"/>`).join('\n    ')}
  </g>
  <text x="420" y="235" font-family="DejaVu Sans, Arial, sans-serif" font-size="52" font-weight="bold" fill="#FFFFFF">SQL Builder</text>
  <text x="420" y="295" font-family="DejaVu Sans, Arial, sans-serif" font-size="40" fill="#DCE7FB">Pro Lite</text>
  <text x="420" y="355" font-family="DejaVu Sans, Arial, sans-serif" font-size="26" fill="#DCE7FB">${BRAND.tagline}</text>
</svg>
`;
}

/** Microsoft Store logo: brand gradient, the symbol in a tile, and the app name (poster 9:16 or box 1:1). */
function storeLogo(width, height) {
    const tile = Math.round(width * 0.46);
    const tileX = (width - tile) / 2;
    const tileY = Math.round(height * (height > width ? 0.26 : 0.18));
    const scale = (tile * 0.62) / 24;
    const off = (tile - 24 * scale) / 2;
    const titleY = tileY + tile + Math.round(width * 0.16);
    const font = Math.round(width * 0.085);
    return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="#1D5FD6"/>
      <stop offset="1" stop-color="#123E91"/>
    </linearGradient>
  </defs>
  <rect width="${width}" height="${height}" fill="url(#bg)"/>
  <rect x="${tileX}" y="${tileY}" width="${tile}" height="${tile}" rx="${tile * 0.18}" fill="#FFFFFF" fill-opacity="0.12"/>
  <g transform="translate(${tileX + off} ${tileY + off}) scale(${scale})" fill="none" stroke="#FFFFFF" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
    ${SYMBOL_PATHS.map(d => `<path d="${d}"/>`).join('\n    ')}
  </g>
  <text x="${width / 2}" y="${titleY}" text-anchor="middle" font-family="DejaVu Sans, Arial, sans-serif" font-size="${font}" font-weight="bold" fill="#FFFFFF">SQL Builder</text>
  <text x="${width / 2}" y="${titleY + Math.round(font * 1.25)}" text-anchor="middle" font-family="DejaVu Sans, Arial, sans-serif" font-size="${Math.round(font * 0.8)}" fill="#DCE7FB">Pro Lite</text>
</svg>
`;
}

async function png(svg, file, size, { opaque = false } = {}) {
    mkdirSync(join(file, '..'), { recursive: true });
    let image = sharp(Buffer.from(svg), { density: 72 }).resize(size.width ?? size, size.height ?? size);
    // Google Play requires the feature graphic without an alpha channel (24-bit PNG)
    if (opaque) image = image.flatten({ background: BRAND.background }).removeAlpha();
    await image.png({ compressionLevel: 9 }).toFile(file);
}

// ---------------------------------------------------------------------- main

async function main() {
    writeFileSync(join(root, 'resources/icon.svg'), artwork(1024));

    if (existsSync(res)) {
        // Remove the Capacitor template placeholders
        for (const dir of ['drawable', 'drawable-v24', 'drawable-land-hdpi', 'drawable-land-mdpi', 'drawable-land-xhdpi', 'drawable-land-xxhdpi',
            'drawable-land-xxxhdpi', 'drawable-port-hdpi', 'drawable-port-mdpi', 'drawable-port-xhdpi', 'drawable-port-xxhdpi', 'drawable-port-xxxhdpi']) {
            for (const name of ['splash.png', 'ic_launcher_foreground.xml', 'ic_launcher_background.xml']) {
                rmSync(join(res, dir, name), { force: true });
            }
        }
        mkdirSync(join(res, 'drawable'), { recursive: true });
        writeFileSync(join(res, 'drawable/ic_launcher_foreground.xml'), vectorDrawable({ color: BRAND.foreground }));
        writeFileSync(join(res, 'drawable/ic_launcher_monochrome.xml'), vectorDrawable({ color: '#FFFFFFFF' }));
        // Android 12+ splash icon: 288dp canvas, content must fit the central 192dp circle
        writeFileSync(join(res, 'drawable/splash_icon.xml'), vectorDrawable({ size: 288, color: BRAND.foreground }));
        writeFileSync(join(res, 'mipmap-anydpi-v26/ic_launcher.xml'), ADAPTIVE_ICON);
        writeFileSync(join(res, 'mipmap-anydpi-v26/ic_launcher_round.xml'), ADAPTIVE_ICON);

        const densities = { mdpi: 48, hdpi: 72, xhdpi: 96, xxhdpi: 144, xxxhdpi: 192 };
        for (const [density, size] of Object.entries(densities)) {
            const dir = join(res, `mipmap-${density}`);
            rmSync(join(dir, 'ic_launcher_foreground.png'), { force: true });
            await png(artwork(size, { shape: 'rounded', symbolFraction: 0.56 }), join(dir, 'ic_launcher.png'), size);
            await png(artwork(size, { shape: 'circle', symbolFraction: 0.52 }), join(dir, 'ic_launcher_round.png'), size);
        }
    }

    // PWA
    await png(artwork(192, { shape: 'rounded', symbolFraction: 0.56 }), join(root, 'icons/icon-192.png'), 192);
    await png(artwork(512, { shape: 'rounded', symbolFraction: 0.56 }), join(root, 'icons/icon-512.png'), 512);
    await png(artwork(512, { shape: 'square', symbolFraction: 0.42 }), join(root, 'icons/icon-maskable-512.png'), 512);
    await png(artwork(180, { shape: 'square', symbolFraction: 0.56 }), join(root, 'icons/apple-touch-icon.png'), 180);

    // Google Play listing
    await png(artwork(512, { shape: 'square', symbolFraction: 0.5 }), join(root, 'store/play-icon-512.png'), 512);
    await png(featureGraphic(), join(root, 'store/feature-graphic-1024x500.png'), { width: 1024, height: 500 }, { opaque: true });

    // Microsoft Store logos (exact sizes Partner Center accepts)
    await png(storeLogo(1440, 2160), join(root, 'store/windows/poster-art-1440x2160.png'), { width: 1440, height: 2160 }, { opaque: true });
    await png(storeLogo(2160, 2160), join(root, 'store/windows/box-art-2160x2160.png'), { width: 2160, height: 2160 }, { opaque: true });

    console.log('Icons generated.');
}

await main();
