table dim_store
	lineageTag: 1d63c925-67d6-4e5c-8eb9-a078939eeab6

	column store_id
		dataType: int64
		formatString: 0
		lineageTag: 806d5439-645b-43e9-b9db-3da7c3165076
		summarizeBy: none
		sourceColumn: store_id

		annotation SummarizationSetBy = Automatic

	column store_name
		dataType: string
		lineageTag: 1f2aaed1-c715-43c1-a8f5-9fd2fc55e6ca
		summarizeBy: none
		sourceColumn: store_name

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 45515f09-1226-4283-86e9-9337fac4da32
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column region_id
		dataType: int64
		formatString: 0
		lineageTag: 17a9423b-b9fe-4025-a62f-87efd5eb6c6e
		summarizeBy: none
		sourceColumn: region_id

		annotation SummarizationSetBy = Automatic

	partition dim_store = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\pappa\Downloads\powerbi-ultimate-course\powerbi-ultimate-course\datasets\04_data_modeling\dim_store.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"store_id", Int64.Type}, {"store_name", type text}, {"city", type text}, {"region_id", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

